sudo: required

language: go

services:
  - docker

env:
  global:
    - secure: Wl4rzxdbsCb/z5gcBwQgfhh2EcCbsd9AVxYm0z5ymOMApSp6zH7gvwv9+BE+Bkphq1cGMo6hBFhpkjVsumnefZTVg2nCYPUmWJv2WdUNIowADPKKdsQQOFaYS83I98xc5h2sKZmUwi6uyvoS0HyEP5RWS9MoyvDoFSC7E1hWzCp+DOB6p0vAYxpClQDXzGu5raBL7EbGltUYvhVaODbEAd1y1vJMxNo/LC9YXtokCcMxAxs1F3hK9eMse3/u420ll7qGf5YN+ve8CqgvpYM41O3j3oqer19P4FEET3WpmUNfqjZLtN1GaV5m0PpVYTzcuyI8aOxGelKRWd03Fd9qsaSvrQIYARJlnrlXjFYmCTAhg5ON/CevO9Bjbsum7vacNdqNf/68w+2WMAt7Y/PGakwaHZ9/wu01+S9LRBkUlJB2K3yUsUNSFjYrM3gRpopupQdOzGMCiGmGGIlbtkUbUZSgzFkEflw9IIg96DOSentq94RYdGigU68093Sq7f/9GNFL/EbLllCGXmHmNnpUdHw3yzVY7oTQI/g1jllLwrO7SQIrb7cDtbZlJwKS8jbpoohKjL6RwoMDh6+e/xn0s2ulTckZd8T2eCvL6SQaV01awNW31TX3yF/h8Bqivko4C9zntLo8srBYlpPEME6DRexfiSJaPQz6dt8IGcUyWSM=
    - secure: Rzyi8+Ou0r1uqw5mHRKZLeT0cWOh1iKqfVz+NyrFc7Lnndw/Llz1Bct9Cl3698+/RGbrZd5xaeP4BzRagbWcfrttmVb0x4LJ+42BN7dw8km7nQyS32jPXGsKktQXbdEeinyche15wN67WyzcMCE0mI6RY4iWtJHnSjb7QrBrS8h8JJvhQhGfhsLiB1tySiKQax7xIi/QpQNt3pr9fWiVoP6tRs+5sfiOFhCEz/v5NlO8Ah6l9o4aVLn8BG7vItNCDEXp9UYOiQCDGfD5U9ec6yDOndTjvKGZdL2ScAqb7k4Wq5zFSnleZEJIg5rsLEzrdBUBwQvVHPQfgF8NQNR9HqVq380QGCRjtWEoVzO/qfO/5Jxv2taITW084nxMYN+nl+lVtf4XoAWtSAR8MOign5f7puZAu7z/hg/Tw1yBD31TMk5Za1K4A6b++u3W8rg/6A9O8WId/kmihuL57xjispoKjMdnD5cAj0aQLTKP7xWMB9BTI/hu7dYg2husXtwEmadFUE+OsXzK3WM0213bSRuPBRoYvGB41UDWscXzxdPCxh8BxKe5BstONh6wxU6J0z/chotTJEWZE9+IKUDf80H8deHLvq7GYCNc4BbZYbRi5+xns5vayW4t0nweUHgxK3T8EP57/bpKE8aMWiQn0gY41ny77D+Js79FDa7s5XM=

before_script:
  - sudo apt-get install curl
  - bash build.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - docker build -t golang-server .
  - docker tag golang-server debarc/golang-server
  - docker run -d -p 8000:8000 debarc/golang-server
  - bash test.sh

after_success:
  - docker push debarc/golang-server