sudo: required

language: go

services:
  - docker

before-script:
  - bash build.sh
  - docker pull debarc/golang-server

script:
  - docker build --pull --cache-from debarc/golang-server --tag debarc/golang-server .
  - docker run debarc/golang-server

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master


